feat(reservations): create a new service category (#7135)
tillhub/tillhub-sdk-javascript pull request #504
Opened 2023-07-20 15:01 UTC by Zarina-Paunova

https://unz.atlassian.net/browse/UNTIL-7135

2023-07-20 15:09 UTC, fullfs approved these changes

2023-07-20 15:11 UTC, maurogri-th requested changes
Think its missing the getAll

2023-07-21 09:21 UTC, fullfs approved these changes

2023-07-21 09:29 UTC, merged

2023-07-21 09:38 UTC, tillhub-engineering commented
:tada: This PR is included in version 4.77.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tillhub/javascript-sdk/v/4.77.0)
- [GitHub release](https://github.com/tillhub/tillhub-sdk-javascript/releases/tag/v4.77.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: